const fmtMoney=n=>new Intl.NumberFormat('vi-VN').format(Math.round(n))+'đ';
const fmtNum=n=>new Intl.NumberFormat('vi-VN').format(Math.round(n));
function toast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent='✓ '+msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1700)}
function setClock(){const c=document.getElementById('clock'),d=document.getElementById('date');if(c){const now=new Date();c.textContent=now.toLocaleTimeString('vi-VN');d.textContent=now.toLocaleDateString('vi-VN')}}setInterval(setClock,1000);setClock();
const open=document.getElementById('openSidebar'),close=document.getElementById('closeSidebar'),sidebar=document.getElementById('sidebar'),overlay=document.getElementById('overlay');function side(v){if(!sidebar)return;sidebar.classList.toggle('open',v);overlay?.classList.toggle('show',v)}open?.addEventListener('click',()=>side(true));close?.addEventListener('click',()=>side(false));overlay?.addEventListener('click',()=>side(false));
let states={1:true,2:false};function updateChannel(n,live){states[n]=live;const card=document.getElementById('channel'+n),status=document.getElementById('status'+n),liveBody=document.getElementById('channel'+n+'LiveBody'),off=document.getElementById('channel'+n+'Offline');if(!card)return;card.classList.toggle('live',live);status.classList.toggle('live',live);status.querySelector('b').textContent=live?'ĐANG LIVE':'OFFLINE';liveBody.classList.toggle('hidden',!live);off.classList.toggle('hidden',live);document.querySelectorAll(`[data-toggle-live="${n}"]`).forEach(b=>b.textContent=live?'Dừng LIVE (Mock)':'Bắt đầu LIVE (Mock)');toast((live?'START ':'STOP ')+'LIVE Channel '+n)}
document.querySelectorAll('[data-toggle-live]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.toggleLive;updateChannel(n,!states[n])}));document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>updateChannel(b.dataset.start,true)));document.querySelectorAll('[data-stop]').forEach(b=>b.addEventListener('click',()=>updateChannel(b.dataset.stop,false)));
let gmv=359081653,orders=4571,ads=7558000;function sync(){const a=document.getElementById('gmv1'),b=document.getElementById('orders1'),c=document.getElementById('ads1');if(a)a.textContent=fmtMoney(gmv);if(b)b.textContent=fmtNum(orders);if(c)c.textContent=fmtMoney(ads)}document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='order'){orders+=1;gmv+=78500;toast('+1 đơn hàng')}if(a==='orders10'){orders+=10;gmv+=785000;toast('+10 đơn hàng')}if(a==='gmv'){gmv+=5000000;toast('+5.000.000đ GMV')}if(a==='ads'){ads+=500000;toast('+500.000đ Ads Spend')}if(a==='cancel')toast('Đã giả lập hủy đơn');if(a==='refund')toast('Đã giả lập hoàn tiền');sync()}));
const select=document.getElementById('snapshotSelect');function snapshot(){if(!select)return;const [mark,rateRaw]=select.value.split('|'),rate=+rateRaw,original=500000000,refund=original*rate/100,net=original-refund;const label=mark==='FINAL'?'FINAL':mark==='0'?'T+0':`T+${mark}H`;document.getElementById('refundMark').textContent=label;document.getElementById('refundAmount').textContent=fmtMoney(refund);document.getElementById('refundRate').textContent=rate.toFixed(1).replace('.',',')+'%';document.getElementById('retainedRevenue').textContent=fmtMoney(net);document.getElementById('rankingSnapshot').textContent=label+' ▾';const total=1211791653;document.getElementById('netGmvLabel').textContent='GMV SAU HOÀN/HỦY • '+label;document.getElementById('netGmvValue').textContent=fmtMoney(total*(1-rate/100));document.getElementById('netGmvRate').textContent='Refund '+rate.toFixed(1).replace('.',',')+'%'}select?.addEventListener('change',snapshot);
document.getElementById('compareToggle')?.addEventListener('click',e=>{const t=document.getElementById('refundTimeline');t.classList.toggle('hidden');e.currentTarget.classList.toggle('primary');e.currentTarget.classList.toggle('secondary')});
