import { useCallback, useEffect, useMemo, useState } from 'react'
import { api, connectDashboardWS, user } from '../lib/api'
import { duration, money, number } from '../lib/format'
import { Bell, BellRing, CheckCircle2, Clock3, Radio, RefreshCw, Wifi } from 'lucide-react'
import { Link } from 'react-router-dom'
function fmtTime(value?:string|null){if(!value)return'Chưa chạy';try{return new Date(value).toLocaleString('vi-VN')}catch{return String(value)}}
export default function LiveControl(){
 const[overview,setOverview]=useState<any>(null);const[monitor,setMonitor]=useState<any>(null);const[message,setMessage]=useState('');const[notify,setNotify]=useState(typeof Notification!=='undefined'?Notification.permission:'unsupported');const isAdmin=user()?.role==='ADMIN'
 const load=useCallback(async()=>{const d:any=await api('/dashboard/overview');setOverview(d);if(isAdmin){try{setMonitor(await api('/integrations/monitor/status'))}catch{}}},[isAdmin])
 useEffect(()=>{load();const stop=connectDashboardWS((event,payload)=>{if(['channel.status','session.updated','refund.updated'].includes(event))load();if(event==='channel.status'){const started=payload.status==='LIVE';setMessage(started?`🔴 ${payload.shop||payload.channel_name||'TikTok'} đã LIVE — hệ thống đã tự tạo phiên và bắt đầu ghi nhận.`:`⏹️ ${payload.shop||payload.channel_name||'TikTok'} đã kết thúc LIVE — hệ thống đã final sync và tạo T+0.`)}});const timer=window.setInterval(load,30000);return()=>{stop();window.clearInterval(timer)}},[load])
 async function enableNotifications(){if(typeof Notification==='undefined'){setMessage('Trình duyệt không hỗ trợ thông báo desktop.');return}const p=await Notification.requestPermission();setNotify(p);setMessage(p==='granted'?'Đã bật thông báo LIVE trên trình duyệt.':'Chưa được cấp quyền thông báo.')}
 const nextCheck=useMemo(()=>!monitor?.last_cycle_at?null:new Date(new Date(monitor.last_cycle_at).getTime()+(monitor.polling_interval_seconds||180)*1000),[monitor])
 if(!overview)return <div className="page-loader">Đang tải giám sát LIVE...</div>
 const shopCount=overview.active_shop_count||overview.channels.length
 return <><div className="page-title"><div><span className="section-kicker">AUTO MONITOR • {shopCount} SHOP</span><h2>Giám sát LIVE tự động</h2><p>Không phát LIVE từ dashboard. Server chỉ nghe tín hiệu từ Shop 1, tự tạo/chốt phiên và đồng bộ dữ liệu đúng chu kỳ 3 phút.</p></div><div className="page-actions"><span className={`mode-badge ${overview.mode==='MOCK'?'mock':'real'}`}>{overview.mode==='MOCK'?'DEMO / MOCK':'API THẬT'}</span><button className="secondary" onClick={load}><RefreshCw size={15}/>Làm mới</button><button className="primary" onClick={enableNotifications}>{notify==='granted'?<BellRing size={15}/>:<Bell size={15}/>} {notify==='granted'?'Thông báo đã bật':'Bật thông báo'}</button></div></div>{message&&<div className="notice">{message}</div>}
 <section className="panel live-monitor-info"><div className="panel-head"><div><span className="section-kicker">AUTOMATION</span><h3>Một state machine duy nhất • 180 giây/lần</h3></div><span className="mode-badge real">3 PHÚT / LẦN</span></div><div className="optional-grid"><div><Wifi size={18}/><small>01 • DETECT</small><b>Kiểm tra tín hiệu Shop 1</b></div><div><Radio size={18}/><small>02 • START</small><b>Thấy LIVE → tự tạo phiên + báo động</b></div><div><RefreshCw size={18}/><small>03 • SYNC</small><b>LIVE • GMV • đơn hàng thật</b></div><div><CheckCircle2 size={18}/><small>04 • END</small><b>OFFLINE → đồng bộ lần cuối rồi đóng phiên</b></div><div><Clock3 size={18}/><small>05 • REFUND</small><b>Tiếp tục cập nhật hoàn/hủy từ TikTok Shop</b></div></div>{isAdmin&&<div className="monitor-meta"><span>Lần kiểm tra gần nhất: <b>{fmtTime(monitor?.last_cycle_at)}</b></span><span>Lần kế tiếp: <b>{nextCheck?nextCheck.toLocaleString('vi-VN'):'Chưa xác định'}</b></span></div>}</section>
 <div className="cards-2">{overview.channels.map((ch:any)=>{const row=monitor?.channels?.find?.((x:any)=>x.channel_id===ch.id);const runtime=row?.runtime||{};const apiLive=runtime.signal==='LIVE';const effectiveLive=apiLive||ch.status==='LIVE';return <article className={`panel monitor-shop ${effectiveLive?'live':''}`} key={ch.id}><div className="panel-head"><div><span className="section-kicker">{row?.name||`SHOP ${ch.id}`} • {ch.name}</span><h3>{ch.handle}</h3></div><span className={`badge ${effectiveLive?'live':'offline'}`}>{effectiveLive?'🔴 ĐANG LIVE':'OFFLINE'}</span></div>{isAdmin&&<div className="signal-strip"><span>Tín hiệu API: <b>{runtime.signal||'CHƯA KIỂM TRA'}</b></span><span>Kiểm tra lúc: <b>{fmtTime(runtime.checked_at)}</b></span>{runtime.error&&<span className="warn">Lỗi: {runtime.error}</span>}</div>}{ch.session?<><div className="notice success-notice">🔴 Đã bắt tín hiệu LIVE • hệ thống đang tự ghi nhận số liệu</div><div className="mock-stats"><div><small>NGUỒN</small><b>TikTok API</b></div><div><small>LIVE TIME</small><b>{duration(ch.session.duration_seconds)}</b></div><div><small>GMV</small><b>{money(ch.session.gmv)}</b></div><div><small>ĐƠN HÀNG</small><b>{number(ch.session.orders)}</b></div></div><Link className="primary action-link" to={`/sessions/${ch.session.id}`}>Xem chi tiết phiên đang ghi nhận</Link></>:apiLive?<div className="notice success-notice">🔴 TikTok đã báo LIVE • hệ thống đang khởi tạo phiên ghi nhận</div>:<div className="offline-content"><Radio size={34}/><div><b>Đang chờ TikTok phát LIVE</b><span>Không cần bấm Start/Stop trên dashboard. Server tự kiểm tra shop này mỗi 180 giây.</span></div></div>}</article>})}</div></>
}
