import { useEffect, useMemo, useState } from 'react'
import { Download, FileSpreadsheet, FileText, RefreshCw } from 'lucide-react'
import { API_BASE, api, token } from '../lib/api'
import { money, number, percent } from '../lib/format'

async function download(path:string,filename:string){const r=await fetch(`${API_BASE}${path}`,{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok)throw new Error('Xuất báo cáo thất bại');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function iso(d:Date){return d.toISOString().slice(0,10)}
export default function Reports(){
 const today=useMemo(()=>iso(new Date()),[]);const[data,setData]=useState<any>(null);const[teams,setTeams]=useState<any[]>([]);const[channels,setChannels]=useState<any[]>([]);const[msg,setMsg]=useState('')
 const[f,setF]=useState<any>({date_from:today,date_to:today,team_id:'',channel_id:'',shift:''})
 const qs=(state=f)=>new URLSearchParams(Object.fromEntries(Object.entries(state).filter(([,v])=>v!=='')) as Record<string,string>).toString()
 async function load(state=f){try{const[d,t,c]:any=await Promise.all([api(`/reports/summary?${qs(state)}`),api('/teams'),api('/channels')]);setData(d);setTeams(t);setChannels(c)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[])
 function preset(kind:'day'|'week'|'month'){const end=new Date();const start=new Date();if(kind==='week')start.setDate(end.getDate()-6);if(kind==='month')start.setDate(1);const next={...f,date_from:iso(start),date_to:iso(end)};setF(next);load(next)}
 async function exp(type:'xlsx'|'pdf'){try{await download(`/reports/export.${type}?${qs()}`,`green-holding-report.${type}`)}catch(e:any){setMsg(e.message)}}
 return <><div className="page-title"><div><span className="section-kicker">REPORT CENTER</span><h2>Báo cáo</h2><p>Lọc theo ngày, team, ca, kênh; xuất Excel/PDF.</p></div><div className="page-actions"><button className="secondary" onClick={()=>preset('day')}>Hôm nay</button><button className="secondary" onClick={()=>preset('week')}>7 ngày</button><button className="secondary" onClick={()=>preset('month')}>Tháng này</button></div></div>{msg&&<div className="notice">{msg}</div>}
 <section className="panel report-filters"><label>Từ ngày<input type="date" value={f.date_from} onChange={e=>setF({...f,date_from:e.target.value})}/></label><label>Đến ngày<input type="date" value={f.date_to} onChange={e=>setF({...f,date_to:e.target.value})}/></label><label>Team<select value={f.team_id} onChange={e=>setF({...f,team_id:e.target.value})}><option value="">Tất cả</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Ca<select value={f.shift} onChange={e=>setF({...f,shift:e.target.value})}><option value="">Tất cả</option><option value="CA_SANG">Ca sáng</option><option value="CA_TOI">Ca tối</option></select></label><label>Kênh<select value={f.channel_id} onChange={e=>setF({...f,channel_id:e.target.value})}><option value="">Tất cả</option>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary" onClick={load}><RefreshCw size={15}/>Áp dụng</button></section>
 {data&&<><section className="kpi-grid six report-kpis"><div className="kpi-card"><small>GMV</small><strong>{money(data.kpis.gmv)}</strong></div><div className="kpi-card"><small>ORDERS</small><strong>{number(data.kpis.orders)}</strong></div><div className="kpi-card"><small>ADS</small><strong>{money(data.kpis.ads_spend)}</strong></div><div className="kpi-card"><small>NET REVENUE</small><strong>{money(data.kpis.net_revenue)}</strong></div><div className="kpi-card"><small>REFUND RATE</small><strong>{percent(data.kpis.refund_rate)}</strong></div><div className="kpi-card"><small>GMV/HOUR</small><strong>{money(data.kpis.gmv_per_hour)}</strong></div></section>
 <div className="report-grid"><article className="panel report-card"><FileSpreadsheet size={34}/><div><h3>Excel Report</h3><p>KPI + ranking + danh sách phiên theo bộ lọc.</p></div><button className="primary" onClick={()=>exp('xlsx')}><Download size={15}/>Tải Excel</button></article><article className="panel report-card"><FileText size={34}/><div><h3>PDF Report</h3><p>Bản tổng hợp theo bộ lọc để gửi lãnh đạo.</p></div><button className="primary" onClick={()=>exp('pdf')}><Download size={15}/>Tải PDF</button></article></div>
 <div className="panel table-panel report-table"><div className="table-scroll"><table><thead><tr><th>#</th><th>TEAM</th><th>GMV</th><th>ORDERS</th><th>AOV</th><th>ADS</th><th>ADS/GMV</th><th>REFUND</th><th>NET</th><th>GMV/HOUR</th></tr></thead><tbody>{data.ranking.map((x:any,i:number)=><tr key={x.team_id}><td>#{i+1}</td><td><b>{x.team_name}</b></td><td>{money(x.gmv)}</td><td>{number(x.orders)}</td><td>{money(x.aov)}</td><td>{money(x.ads)}</td><td>{percent(x.ads_percentage)}</td><td>{percent(x.refund_rate)}</td><td>{money(x.net)}</td><td>{money(x.gmv_per_hour)}</td></tr>)}</tbody></table></div></div></>}
 </>
}
