import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, connectDashboardWS } from '../lib/api'
import { compactMoney, dt, duration, money, number, percent } from '../lib/format'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { KpiCard } from '../components/Cards'
import { RefreshCw } from 'lucide-react'

const sourceLabel: Record<string,string> = {
  LIVE_CURRENT:'LIVE hiện tại', LIVE_OTHER:'LIVE khác', LIVE_UNMATCHED:'LIVE chưa ghép được',
  VIDEO:'Video', LINKSHARE:'Link affiliate', SHOP:'Shop / Showcase', PRE_LIVE:'Pre-LIVE',
  PROMOTION_PAGE:'Trang khuyến mãi', UNKNOWN:'Chưa xác định'
}

export default function SessionDetail(){
  const {id}=useParams(); const [data,setData]=useState<any>(null); const [selected,setSelected]=useState(''); const [compare,setCompare]=useState(true)
  const load=useCallback(()=>api(`/sessions/${id}`).then((x:any)=>{setData(x);if(!selected&&x.refund_snapshots?.length)setSelected(x.refund_snapshots[x.refund_snapshots.length-1].snapshot_type)}),[id,selected])
  useEffect(()=>{load();const stop=connectDashboardWS((_,p)=>{if(!p?.session_id||String(p.session_id)===String(id))load()});return stop},[load,id])
  const snap=data?.refund_snapshots?.find((x:any)=>x.snapshot_type===selected)
  const timeline=useMemo(()=>data?.timeline?.map((x:any)=>({...x,time:new Date(x.timestamp).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}))||[],[data])
  if(!data)return <div className="page-loader">Đang tải phiên LIVE...</div>
  const core=data.live_core_latest; const attr=data.attribution; const sources=attr?.sources||[]
  return <>
    <div className="page-title"><div><Link className="back-link" to="/sessions">← Phiên LIVE</Link><span className="section-kicker">{data.session_code}</span><h2>{data.team_name} • {data.channel_name}</h2><p>{data.shift==='CA_SANG'?'Ca sáng':'Ca tối'} • Bắt đầu {dt(data.started_at)} • Nguồn {data.source}</p></div><div className="page-actions"><span className={`mode-badge ${data.status==='LIVE'?'real':'ended'}`}>{data.status==='LIVE'?'TỰ ĐỘNG GHI NHẬN':'ĐÃ KẾT THÚC'}</span><button className="secondary" onClick={load}><RefreshCw size={15}/>Làm mới</button></div></div>
    <div className="session-hero"><div><small>LIVE TIME</small><strong>{duration(data.duration_seconds)}</strong></div><div><small>BẮT ĐẦU</small><b>{dt(data.started_at)}</b></div><div><small>KẾT THÚC</small><b>{dt(data.ended_at)}</b></div></div>
    <section className="kpi-grid six"><KpiCard label="LIVE GMV" value={money(data.gmv)} sub={data.metric_source==='TIKTOK_LIVE_ANALYTICS'?'TikTok LIVE Analytics':'Exact attributed orders'}/><KpiCard label="LIVE ORDERS" value={number(data.orders)}/><KpiCard label="AOV" value={money(data.aov)}/><KpiCard label="ADS SPEND" value={money(data.ads_spend)}/><KpiCard label="ADS / LIVE GMV" value={percent(data.ads_percentage)}/><KpiCard label="ROAS" value={data.roas?.toFixed?.(1)||'0.0'}/></section>

    <section className="panel"><div className="panel-head"><div><span className="section-kicker">ORDER ATTRIBUTION</span><h3>Phân biệt đơn LIVE và nguồn khác</h3><p className="muted">Không dùng thời gian đặt đơn để suy đoán. Chỉ content_type=LIVE + content_id trùng phiên mới được gắn vào LIVE hiện tại.</p></div></div>
      {sources.length?<div className="table-scroll"><table><thead><tr><th>Nguồn TikTok</th><th>Số đơn affiliate</th><th>SKU rows</th><th>GMV attribution</th><th>Xử lý</th></tr></thead><tbody>{sources.map((s:any)=><tr key={s.source}><td><b>{sourceLabel[s.source]||s.source}</b></td><td>{number(s.orders)}</td><td>{number(s.sku_rows)}</td><td>{money(s.gmv)}</td><td>{s.source==='LIVE_CURRENT'?<span className="badge live">TÍNH VÀO LIVE</span>:<span className="badge ended">KHÔNG TÍNH VÀO LIVE</span>}</td></tr>)}</tbody></table></div>:<div className="empty">Chưa có dữ liệu attribution. Khi scope Affiliate Orders được cấp, hệ thống sẽ tự tách LIVE / VIDEO / LINKSHARE / SHOP.</div>}
      <div className="notice">LIVE GMV phía trên lấy từ TikTok LIVE Analytics. Bảng này dùng để truy vết chính xác từng đơn affiliate theo nguồn; đơn chưa được API xác nhận sẽ giữ UNKNOWN và không tự cộng vào LIVE.</div>
    </section>

    {core&&<section className="panel"><div className="panel-head"><div><span className="section-kicker">LIVE CORE METRICS</span><h3>Chỉ số từ API LIVE gần nhất</h3></div><small>{dt(core.captured_at)}</small></div><div className="optional-grid live-core-grid"><div><small>GMV API LIVE</small><b>{core.gmv==null?'Chưa có':money(core.gmv)}</b></div><div><small>ORDERS</small><b>{core.orders==null?'Chưa có':number(core.orders)}</b></div><div><small>PAID ORDERS</small><b>{core.paid_orders==null?'Chưa có':number(core.paid_orders)}</b></div><div><small>CURRENT VIEWERS</small><b>{core.current_viewers==null?'Chưa có':number(core.current_viewers)}</b></div><div><small>PEAK VIEWERS</small><b>{core.peak_viewers==null?'Chưa có':number(core.peak_viewers)}</b></div><div><small>BUYERS</small><b>{core.buyers==null?'Chưa có':number(core.buyers)}</b></div><div><small>PRODUCT VIEWS</small><b>{core.product_views==null?'Chưa có':number(core.product_views)}</b></div><div><small>CTR</small><b>{core.ctr==null?'Chưa có':percent(core.ctr)}</b></div><div><small>COMMENTS</small><b>{core.comments==null?'Chưa có':number(core.comments)}</b></div><div><small>SHARES</small><b>{core.shares==null?'Chưa có':number(core.shares)}</b></div></div></section>}

    <section className="dashboard-grid"><article className="panel span-2"><div className="panel-head"><div><span className="section-kicker">LIVE TIMELINE</span><h3>GMV theo thời gian • snapshot 3 phút/lần</h3></div><strong>{compactMoney(data.gmv)}</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline}><CartesianGrid stroke="#e1e8e4" vertical={false}/><XAxis dataKey="time" stroke="#7a8b83"/><YAxis stroke="#7a8b83" tickFormatter={compactMoney}/><Tooltip contentStyle={{background:'#fff',border:'1px solid #dce5e0',borderRadius:10}} formatter={(v:any)=>money(Number(v))}/><Area type="monotone" dataKey="gmv" stroke="#18a968" fill="#18a96822"/></AreaChart></ResponsiveContainer></div></article><article className="panel refund-select-panel"><div className="panel-head"><div><span className="section-kicker">REFUND SNAPSHOT</span><h3>Mốc đánh giá</h3></div></div>{data.refund_snapshots.length?<><select value={selected} onChange={e=>setSelected(e.target.value)}>{data.refund_snapshots.map((x:any)=><option key={x.id} value={x.snapshot_type}>{x.snapshot_type==='T+0'?'Ngay sau LIVE':x.snapshot_type}</option>)}</select><div className="refund-big"><small>Tỷ lệ hoàn/hủy</small><strong>{percent(snap?.refund_cancel_rate)}</strong></div><div className="refund-values"><div><small>GMV ban đầu</small><b>{money(snap?.original_gmv)}</b></div><div><small>Hoàn tiền</small><b>{money(snap?.refund_amount)}</b></div><div><small>Hủy</small><b>{money(snap?.cancelled_amount)}</b></div><div><small>Doanh thu giữ</small><b>{money(snap?.net_revenue)}</b></div></div><label className="switch-row"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/> SO SÁNH CÁC MỐC</label></>:<div className="empty">Snapshot được tạo tự động từ T+0 sau khi TikTok báo OFFLINE.</div>}</article></section>
    {compare&&data.refund_snapshots.length>0&&<section className="panel"><div className="panel-head"><div><span className="section-kicker">REFUND TIMELINE</span><h3>Tỷ lệ hoàn/hủy qua các mốc</h3></div></div><div className="chart-box short"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.refund_snapshots}><CartesianGrid stroke="#e1e8e4" vertical={false}/><XAxis dataKey="snapshot_type" stroke="#7a8b83"/><YAxis stroke="#7a8b83" unit="%"/><Tooltip contentStyle={{background:'#fff',border:'1px solid #dce5e0',borderRadius:10}} formatter={(v:any)=>percent(Number(v))}/><Line type="monotone" dataKey="refund_cancel_rate" stroke="#d98a13" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section>}
  </>
}
