import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, connectDashboardWS, user } from '../lib/api'
import { compactMoney, dt, duration, money, number, percent } from '../lib/format'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, LineChart, Line } from 'recharts'
import { KpiCard } from '../components/Cards'
import { RefreshCw, StopCircle } from 'lucide-react'

export default function SessionDetail(){
  const {id}=useParams(); const [data,setData]=useState<any>(null); const [selected,setSelected]=useState(''); const [compare,setCompare]=useState(true)
  const load=useCallback(()=>api(`/sessions/${id}`).then(x=>{setData(x); if(!selected&&x.refund_snapshots?.length)setSelected(x.refund_snapshots[x.refund_snapshots.length-1].snapshot_type)}),[id,selected])
  useEffect(()=>{load(); const stop=connectDashboardWS((_,p)=>{if(!p?.session_id||String(p.session_id)===String(id))load()}); return stop},[load,id])
  const snap=data?.refund_snapshots?.find((x:any)=>x.snapshot_type===selected)
  const timeline=useMemo(()=>data?.timeline?.map((x:any)=>({...x,time:new Date(x.timestamp).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}))||[],[data])
  if(!data)return <div className="page-loader">Đang tải phiên LIVE...</div>
  async function stop(){await api(`/sessions/${id}/stop`,{method:'POST'});await load()}
  return <><div className="page-title"><div><Link className="back-link" to="/sessions">← Phiên LIVE</Link><span className="section-kicker">{data.session_code}</span><h2>{data.team_name} • {data.channel_name}</h2><p>{data.shift==='CA_SANG'?'Ca sáng':'Ca tối'} • Bắt đầu {dt(data.started_at)} • Source {data.source}</p></div><div className="page-actions"><span className={`mode-badge ${data.status==='LIVE'?'real':'ended'}`}>{data.status}</span>{data.status==='LIVE'&&user()?.role==='ADMIN'&&<button className="danger" onClick={stop}><StopCircle size={15}/>Dừng LIVE</button>}<button className="secondary" onClick={load}><RefreshCw size={15}/>Làm mới</button></div></div>
  <div className="session-hero"><div><small>LIVE TIME</small><strong>{duration(data.duration_seconds)}</strong></div><div><small>BẮT ĐẦU</small><b>{dt(data.started_at)}</b></div><div><small>KẾT THÚC</small><b>{dt(data.ended_at)}</b></div></div>
  <section className="kpi-grid six"><KpiCard label="GMV" value={money(data.gmv)}/><KpiCard label="ORDERS" value={number(data.orders)}/><KpiCard label="AOV" value={money(data.aov)}/><KpiCard label="ADS SPEND" value={money(data.ads_spend)}/><KpiCard label="ADS / GMV" value={percent(data.ads_percentage)}/><KpiCard label="ROAS" value={data.roas?.toFixed?.(1)||'0.0'}/></section>
  <section className="dashboard-grid"><article className="panel span-2"><div className="panel-head"><div><span className="section-kicker">LIVE TIMELINE</span><h3>GMV theo thời gian</h3></div><strong>{compactMoney(data.gmv)}</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline}><CartesianGrid stroke="#173126" vertical={false}/><XAxis dataKey="time" stroke="#63786e"/><YAxis stroke="#63786e" tickFormatter={compactMoney}/><Tooltip contentStyle={{background:'#0b1712',border:'1px solid #244335'}} formatter={(v:any)=>money(Number(v))}/><Area type="monotone" dataKey="gmv" stroke="#36e189" fill="#36e18922"/></AreaChart></ResponsiveContainer></div></article>
  <article className="panel refund-select-panel"><div className="panel-head"><div><span className="section-kicker">REFUND SNAPSHOT</span><h3>Mốc đánh giá</h3></div></div>{data.refund_snapshots.length?<><select value={selected} onChange={e=>setSelected(e.target.value)}>{data.refund_snapshots.map((x:any)=><option key={x.id} value={x.snapshot_type}>{x.snapshot_type==='T+0'?'Ngay sau LIVE':x.snapshot_type}</option>)}</select><div className="refund-big"><small>Tỷ lệ hoàn/hủy</small><strong>{percent(snap?.refund_cancel_rate)}</strong></div><div className="refund-values"><div><small>GMV ban đầu</small><b>{money(snap?.original_gmv)}</b></div><div><small>Hoàn tiền</small><b>{money(snap?.refund_amount)}</b></div><div><small>Hủy</small><b>{money(snap?.cancelled_amount)}</b></div><div><small>Doanh thu giữ</small><b>{money(snap?.net_revenue)}</b></div></div><label className="switch-row"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/> SO SÁNH CÁC MỐC</label></>:<div className="empty">Snapshot được tạo từ T+0 sau khi phiên kết thúc.</div>}</article></section>
  {compare&&data.refund_snapshots.length>0&&<section className="panel"><div className="panel-head"><div><span className="section-kicker">REFUND TIMELINE</span><h3>Tỷ lệ hoàn/hủy qua các mốc</h3></div></div><div className="chart-box short"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.refund_snapshots}><CartesianGrid stroke="#173126" vertical={false}/><XAxis dataKey="snapshot_type" stroke="#63786e"/><YAxis stroke="#63786e" unit="%"/><Tooltip contentStyle={{background:'#0b1712',border:'1px solid #244335'}} formatter={(v:any)=>percent(Number(v))}/><Line type="monotone" dataKey="refund_cancel_rate" stroke="#ffb84d" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section>}
  </>
}
