import { useEffect,useState } from 'react'
import { api,json } from '../lib/api'
import { CalendarDays,CheckCircle2,ChevronLeft,ChevronRight,CircleAlert,Radio,RefreshCw,ShieldCheck } from 'lucide-react'

function Flag({label,ok,value}:{label:string,ok?:boolean,value?:any}){return <div><span>{label}</span><b className={ok?'ok-text':'muted'}>{value??(ok?'Đã cấu hình':'Chưa cấu hình')}</b></div>}
function todayVN(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const x:any={};p.forEach(i=>x[i.type]=i.value);return `${x.year}-${x.month}-${x.day}`}
function moveDate(value:string,days:number){const d=new Date(`${value}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function prettyDate(value:string){return new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(`${value}T12:00:00+07:00`))}

export default function Settings(){
 const[status,setStatus]=useState<any>(null);const[thresholds,setThresholds]=useState<any>(null);const[teams,setTeams]=useState<any[]>([]);const[message,setMessage]=useState('');const[scheduleDate,setScheduleDate]=useState(todayVN());const[schedule,setSchedule]=useState<any>(null)
 const loadBase=()=>Promise.all([api('/integrations/status'),api('/settings/thresholds'),api('/teams')]).then(([s,t,tm]:any)=>{setStatus(s);setThresholds(t);setTeams(tm)})
 const loadSchedule=(date:string)=>{setSchedule(null);return api(`/settings/daily-schedule/${date}`).then((x:any)=>setSchedule(x))}
 useEffect(()=>{loadBase()},[]);useEffect(()=>{loadSchedule(scheduleDate)},[scheduleDate])
 async function test(kind:'shop'|'ads'|'live',channelId:number){setMessage(`Đang test ${kind.toUpperCase()} Shop ${channelId}...`);try{const r:any=await api(`/integrations/test/${kind}/${channelId}`,{method:'POST'});setMessage(`${kind.toUpperCase()} Shop ${channelId}: OK${r.result?.status?` • ${r.result.status}`:''}`)}catch(e:any){setMessage(e.message)}}
 async function saveThresholds(){await api('/settings/thresholds',json('PATCH',thresholds));setMessage('Đã lưu ngưỡng cảnh báo')}
 async function saveSchedule(){const r:any=await api(`/settings/daily-schedule/${scheduleDate}`,json('PUT',schedule));setSchedule(r);setMessage(`Đã lưu lịch phân ca ${prettyDate(scheduleDate)}`)}
 if(!status||!thresholds||!schedule)return <div className="page-loader">Đang tải cấu hình...</div>
 const shopCount=status.active_shop_count||status.shops.length;const requiredShifts=shopCount*2
 const teamSelect=(key:string)=><select value={schedule[key]??''} onChange={e=>setSchedule({...schedule,[key]:e.target.value?Number(e.target.value):null})}><option value="">— Chưa phân ca —</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
 return <><div className="page-title"><div><span className="section-kicker">API INTEGRATION CENTER</span><h2>{shopCount} Shop • API riêng cho Shop 1</h2><p>Secret/token chỉ nhập trong Render Environment. Dashboard chỉ hiển thị trạng thái đã/chưa cấu hình.</p></div><button className="secondary" onClick={()=>{loadBase();loadSchedule(scheduleDate)}}><RefreshCw size={15}/>Refresh</button></div>{message&&<div className="notice">{message}</div>}
 <section className="panel monitor-summary"><div className="panel-head"><div><span className="section-kicker">PRODUCTION FLOW</span><h3>{status.data_provider} / {status.live_status_provider}</h3></div><span className="mode-badge real">{status.polling_interval_seconds}s / lần</span></div><p className="muted">Khi đã kiểm tra quyền API thành công: đặt <code>DATA_PROVIDER=TIKTOK</code> và <code>LIVE_STATUS_PROVIDER=AUTO</code>. Hệ thống hiện chỉ dùng credential của Shop 1.</p></section>
 <div className="cards-2">{status.shops.map((s:any)=>{const shopConnected=s.shop.app_key&&s.shop.app_secret&&s.shop.access_token&&s.shop.refresh_token&&s.shop.shop_cipher&&s.shop.shop_id;return <section className="panel" key={s.channel_id}><div className="panel-head"><div><span className="section-kicker">{s.name}</span><h3>{s.channel_name}</h3></div>{shopConnected?<CheckCircle2 className="ok"/>:<CircleAlert className="warn"/>}</div><div className="status-list"><Flag label="Shop App Key" ok={s.shop.app_key}/><Flag label="Shop App Secret" ok={s.shop.app_secret}/><Flag label="Shop Access Token" ok={s.shop.access_token}/><Flag label="Shop Refresh Token" ok={s.shop.refresh_token}/><Flag label="Shop Cipher" ok={s.shop.shop_cipher}/><Flag label="Shop ID" ok={!!s.shop.shop_id} value={s.shop.shop_id||'Chưa cấu hình'}/><Flag label="Ads Access Token" ok={s.ads.access_token}/><Flag label="Advertiser ID" ok={!!s.ads.advertiser_id} value={s.ads.advertiser_id||'Chưa cấu hình'}/><Flag label="LIVE Status API" ok={s.live.status_endpoint}/><Flag label="LIVE Metrics API" ok={s.live.metrics_endpoint}/><Flag label="LIVE Auth" ok={true} value={s.live.status_auth_mode}/></div><div className="inline-actions"><button className="secondary" onClick={()=>test('live',s.channel_id)}><Radio size={14}/>Test LIVE</button><button className="secondary" onClick={()=>test('shop',s.channel_id)}>Test Shop</button><button className="secondary" onClick={()=>test('ads',s.channel_id)}>Test Ads</button></div></section>})}</div>
 <div className="settings-grid"><section className="panel"><div className="panel-head"><div><span className="section-kicker">ALERT THRESHOLDS</span><h3>Ngưỡng cảnh báo</h3></div></div><label>Hoàn/Hủy vượt (%)<input type="number" value={thresholds.refund_warning_percent} onChange={e=>setThresholds({...thresholds,refund_warning_percent:+e.target.value})}/></label><label>Ads/GMV vượt (%)<input type="number" value={thresholds.ads_gmv_warning_percent} onChange={e=>setThresholds({...thresholds,ads_gmv_warning_percent:+e.target.value})}/></label><label>GMV 15 phút giảm (%)<input type="number" value={thresholds.gmv_velocity_drop_percent} onChange={e=>setThresholds({...thresholds,gmv_velocity_drop_percent:+e.target.value})}/></label><button className="primary" onClick={saveThresholds}>Lưu thresholds</button></section>
 <section className="panel"><div className="panel-head"><div><span className="section-kicker">DAILY LIVE SCHEDULE</span><h3>Lịch phân ca theo ngày</h3><p className="muted">Phiên LIVE mới sẽ lấy team theo ngày Việt Nam tại thời điểm bắt đầu.</p></div>{schedule.complete?<CheckCircle2 className="ok"/>:<CircleAlert className="warn"/>}</div>
 <div className="inline-actions" style={{marginBottom:16,alignItems:'center',flexWrap:'wrap'}}><button className="secondary" onClick={()=>setScheduleDate(moveDate(scheduleDate,-1))}><ChevronLeft size={15}/>Ngày trước</button><label style={{margin:0,minWidth:190}}><span style={{display:'block',fontSize:11,marginBottom:5}}>Ngày áp dụng</span><input type="date" value={scheduleDate} onChange={e=>setScheduleDate(e.target.value)}/></label><button className="secondary" onClick={()=>setScheduleDate(todayVN())}><CalendarDays size={15}/>Hôm nay</button><button className="secondary" onClick={()=>setScheduleDate(moveDate(scheduleDate,1))}>Ngày sau<ChevronRight size={15}/></button></div>
 <div className="notice" style={{marginBottom:14}}><b>{prettyDate(scheduleDate)}</b> • {schedule.complete?`Đã phân đủ ${requiredShifts} ca`:`Chưa phân đủ ${requiredShifts} ca — nếu TikTok LIVE ở ô chưa có team, hệ thống sẽ cảnh báo và không tự gán nhầm.`}</div>
 <div className="assignment-grid"><label>Kênh 01 • Ca sáng{teamSelect('channel_1_ca_sang_team_id')}</label><label>Kênh 01 • Ca tối{teamSelect('channel_1_ca_toi_team_id')}</label>{shopCount>1&&<><label>Kênh 02 • Ca sáng{teamSelect('channel_2_ca_sang_team_id')}</label><label>Kênh 02 • Ca tối{teamSelect('channel_2_ca_toi_team_id')}</label></>}</div><button className="primary" onClick={saveSchedule}>Lưu lịch ngày {scheduleDate.split('-').reverse().join('/')}</button></section></div>
 <section className="panel env-panel"><div className="panel-head"><div><span className="section-kicker">RENDER ENV</span><h3>Nhóm biến cần điền khi TikTok cấp API</h3></div><ShieldCheck className="ok"/></div><div className="code-list"><code>ACTIVE_SHOP_COUNT=1</code><code>DATA_PROVIDER=TIKTOK</code><code>LIVE_STATUS_PROVIDER=AUTO</code><code>TIKTOK_SHOP_APP_KEY / TIKTOK_SHOP_APP_SECRET / TIKTOK_OAUTH_STATE</code><code>SHOP1_SHOP_CIPHER / SHOP1_SHOP_ID</code><code>SHOP1_LIVE_STATUS_URL + JSON_PATH + LIVE/OFFLINE VALUE</code><code>SHOP1_ADS_ACCESS_TOKEN / ADVERTISER_ID</code><code>POLLING_INTERVAL_SECONDS=180</code></div></section></>
}
