import { useEffect,useState } from 'react'
import { api,json } from '../lib/api'
import { CheckCircle2,CircleAlert,Radio,RefreshCw,ShieldCheck } from 'lucide-react'
function Flag({label,ok,value}:{label:string,ok?:boolean,value?:any}){return <div><span>{label}</span><b className={ok?'ok-text':'muted'}>{value??(ok?'Đã cấu hình':'Chưa cấu hình')}</b></div>}
export default function Settings(){
 const[status,setStatus]=useState<any>(null);const[thresholds,setThresholds]=useState<any>(null);const[assignments,setAssignments]=useState<any>(null);const[teams,setTeams]=useState<any[]>([]);const[message,setMessage]=useState('')
 const load=()=>Promise.all([api('/integrations/status'),api('/settings/thresholds'),api('/settings/assignments'),api('/teams')]).then(([s,t,a,tm]:any)=>{setStatus(s);setThresholds(t);setAssignments(a);setTeams(tm)});useEffect(()=>{load()},[])
 async function test(kind:'shop'|'ads'|'live',channelId:number){setMessage(`Đang test ${kind.toUpperCase()} Shop ${channelId}...`);try{const r:any=await api(`/integrations/test/${kind}/${channelId}`,{method:'POST'});setMessage(`${kind.toUpperCase()} Shop ${channelId}: OK${r.result?.status?` • ${r.result.status}`:''}`)}catch(e:any){setMessage(e.message)}}
 async function saveThresholds(){await api('/settings/thresholds',json('PATCH',thresholds));setMessage('Đã lưu ngưỡng cảnh báo')}async function saveAssignments(){await api('/settings/assignments',json('PATCH',assignments));setMessage('Đã lưu team phụ trách theo kênh/ca')}
 if(!status||!thresholds||!assignments)return <div className="page-loader">Đang tải cấu hình...</div>
 const teamSelect=(key:string)=><select value={assignments[key]||''} onChange={e=>setAssignments({...assignments,[key]:+e.target.value})}><option value="">Chọn team</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
 return <><div className="page-title"><div><span className="section-kicker">API INTEGRATION CENTER</span><h2>2 Shop • 2 bộ API độc lập</h2><p>Secret/token chỉ nhập trong Render Environment. Dashboard chỉ hiển thị trạng thái đã/chưa cấu hình.</p></div><button className="secondary" onClick={load}><RefreshCw size={15}/>Refresh</button></div>{message&&<div className="notice">{message}</div>}
 <section className="panel monitor-summary"><div className="panel-head"><div><span className="section-kicker">PRODUCTION FLOW</span><h3>{status.data_provider} / {status.live_status_provider}</h3></div><span className="mode-badge real">{status.polling_interval_seconds}s / lần</span></div><p className="muted">Khi có API thật: đặt <code>DATA_PROVIDER=TIKTOK</code> và <code>LIVE_STATUS_PROVIDER=AUTO</code>. Mỗi shop dùng credential riêng; không dùng chéo token.</p></section>
 <div className="cards-2">{status.shops.map((s:any)=><section className="panel" key={s.channel_id}><div className="panel-head"><div><span className="section-kicker">{s.name}</span><h3>{s.channel_name}</h3></div>{s.shop.access_token&&s.live.status_endpoint?<CheckCircle2 className="ok"/>:<CircleAlert className="warn"/>}</div><div className="status-list"><Flag label="Shop App Key" ok={s.shop.app_key}/><Flag label="Shop App Secret" ok={s.shop.app_secret}/><Flag label="Shop Access Token" ok={s.shop.access_token}/><Flag label="Shop Refresh Token" ok={s.shop.refresh_token}/><Flag label="Shop Cipher" ok={s.shop.shop_cipher}/><Flag label="Shop ID" ok={!!s.shop.shop_id} value={s.shop.shop_id||'Chưa cấu hình'}/><Flag label="Ads Access Token" ok={s.ads.access_token}/><Flag label="Advertiser ID" ok={!!s.ads.advertiser_id} value={s.ads.advertiser_id||'Chưa cấu hình'}/><Flag label="LIVE Status API" ok={s.live.status_endpoint}/><Flag label="LIVE Metrics API" ok={s.live.metrics_endpoint}/><Flag label="LIVE Auth" ok={true} value={s.live.status_auth_mode}/></div><div className="inline-actions"><button className="secondary" onClick={()=>test('live',s.channel_id)}><Radio size={14}/>Test LIVE</button><button className="secondary" onClick={()=>test('shop',s.channel_id)}>Test Shop</button><button className="secondary" onClick={()=>test('ads',s.channel_id)}>Test Ads</button></div></section>)}</div>
 <div className="settings-grid"><section className="panel"><div className="panel-head"><div><span className="section-kicker">ALERT THRESHOLDS</span><h3>Ngưỡng cảnh báo</h3></div></div><label>Hoàn/Hủy vượt (%)<input type="number" value={thresholds.refund_warning_percent} onChange={e=>setThresholds({...thresholds,refund_warning_percent:+e.target.value})}/></label><label>Ads/GMV vượt (%)<input type="number" value={thresholds.ads_gmv_warning_percent} onChange={e=>setThresholds({...thresholds,ads_gmv_warning_percent:+e.target.value})}/></label><label>GMV 15 phút giảm (%)<input type="number" value={thresholds.gmv_velocity_drop_percent} onChange={e=>setThresholds({...thresholds,gmv_velocity_drop_percent:+e.target.value})}/></label><button className="primary" onClick={saveThresholds}>Lưu thresholds</button></section><section className="panel"><div className="panel-head"><div><span className="section-kicker">AUTO TEAM MAPPING</span><h3>Team theo kênh / ca</h3></div></div><div className="assignment-grid"><label>Kênh 01 • Ca sáng{teamSelect('channel_1_ca_sang_team_id')}</label><label>Kênh 01 • Ca tối{teamSelect('channel_1_ca_toi_team_id')}</label><label>Kênh 02 • Ca sáng{teamSelect('channel_2_ca_sang_team_id')}</label><label>Kênh 02 • Ca tối{teamSelect('channel_2_ca_toi_team_id')}</label></div><button className="primary" onClick={saveAssignments}>Lưu phân ca</button></section></div>
 <section className="panel env-panel"><div className="panel-head"><div><span className="section-kicker">RENDER ENV</span><h3>Nhóm biến cần điền khi TikTok cấp API</h3></div><ShieldCheck className="ok"/></div><div className="code-list"><code>DATA_PROVIDER=TIKTOK</code><code>LIVE_STATUS_PROVIDER=AUTO</code><code>SHOP1_APP_KEY / APP_SECRET / ACCESS_TOKEN / REFRESH_TOKEN / SHOP_CIPHER / SHOP_ID</code><code>SHOP1_LIVE_STATUS_URL + JSON_PATH + LIVE/OFFLINE VALUE</code><code>SHOP1_ADS_ACCESS_TOKEN / ADVERTISER_ID</code><code>SHOP2_* tương tự nhưng hoàn toàn độc lập</code><code>POLLING_INTERVAL_SECONDS=180</code></div></section></>
}
