import { useEffect, useState } from 'react'
import { api, json } from '../lib/api'
import { CheckCircle2, CircleAlert, RefreshCw } from 'lucide-react'

const envs=['DATA_PROVIDER=TIKTOK','LIVE_STATUS_PROVIDER=MANUAL','TIKTOK_SHOP_APP_KEY=','TIKTOK_SHOP_APP_SECRET=','TIKTOK_SHOP_ACCESS_TOKEN=','TIKTOK_SHOP_REFRESH_TOKEN=','TIKTOK_ADS_APP_ID=','TIKTOK_ADS_SECRET=','TIKTOK_ADS_ACCESS_TOKEN=']
function Status({label,ok}:{label:string,ok:boolean}){return <div><span>{label}</span><b className={ok?'ok-text':'muted'}>{ok?'Đã cấu hình':'Chưa cấu hình'}</b></div>}

export default function Settings(){
 const[s,setS]=useState<any>(null);const[t,setT]=useState<any>(null);const[a,setA]=useState<any>(null);const[teams,setTeams]=useState<any[]>([]);const[msg,setMsg]=useState('')
 const load=()=>Promise.all([api('/integrations/status'),api('/settings/thresholds'),api('/settings/assignments'),api('/teams')]).then(([s0,t0,a0,tm]:any)=>{setS(s0);setT(t0);setA(a0);setTeams(tm)})
 useEffect(()=>{load()},[])
 async function saveThresholds(){await api('/settings/thresholds',json('PATCH',t));setMsg('Đã lưu ngưỡng cảnh báo')}
 async function saveAssignments(){await api('/settings/assignments',json('PATCH',a));setMsg('Đã lưu team phụ trách theo kênh/ca')}
 async function testShop(){setMsg('Đang test TikTok Shop...');try{const r:any=await api('/integrations/test/shop',{method:'POST'});setMsg(`TikTok Shop OK • ${r.shops?.length||0} shop được cấp quyền`)}catch(e:any){setMsg(e.message)}}
 async function testAds(channel:number){setMsg(`Đang test TikTok Ads kênh ${channel}...`);try{await api(`/integrations/test/ads/${channel}`,{method:'POST'});setMsg(`TikTok Ads kênh ${channel} OK`)}catch(e:any){setMsg(e.message)}}
 if(!s||!t||!a)return <div className="page-loader">Đang tải cấu hình...</div>
 const teamSelect=(key:string)=><select value={a[key]||''} onChange={e=>setA({...a,[key]:+e.target.value})}><option value="">Chọn team</option>{teams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
 return <><div className="page-title"><div><span className="section-kicker">INTEGRATION CENTER</span><h2>Cấu hình API</h2><p>Secret/token chỉ ở backend ENV, không bao giờ đưa xuống frontend.</p></div><button className="secondary" onClick={load}><RefreshCw size={15}/>Refresh</button></div>{msg&&<div className="notice">{msg}</div>}
 <div className="settings-grid">
  <section className="panel"><div className="panel-head"><div><span className="section-kicker">TIKTOK SHOP</span><h3>Shop Open API</h3></div>{s.shop.app_key&&s.shop.app_secret&&s.shop.access_token?<CheckCircle2 className="ok"/>:<CircleAlert className="warn"/>}</div><div className="status-list"><Status label="App Key" ok={s.shop.app_key}/><Status label="App Secret" ok={s.shop.app_secret}/><Status label="Access Token" ok={s.shop.access_token}/><Status label="Refresh Token" ok={s.shop.refresh_token}/></div><button className="secondary" onClick={testShop}>Test Authorized Shops</button></section>
  <section className="panel"><div className="panel-head"><div><span className="section-kicker">TIKTOK ADS</span><h3>Marketing API</h3></div>{s.ads.access_token?<CheckCircle2 className="ok"/>:<CircleAlert className="warn"/>}</div><div className="status-list"><Status label="App ID" ok={s.ads.app_id}/><Status label="Secret" ok={s.ads.secret}/><Status label="Access Token" ok={s.ads.access_token}/><div><span>Metrics</span><b>{s.ads.metrics.join(', ')}</b></div><div><span>Revenue metric</span><b>{s.ads.revenue_metric||'Chưa cấu hình (optional)'}</b></div></div><div className="inline-actions">{s.channels.map((x:any)=><button className="secondary" key={x.id} onClick={()=>testAds(x.id)}>Test Ads {x.name}</button>)}</div></section>
  <section className="panel"><div className="panel-head"><div><span className="section-kicker">LIVE DETECTION</span><h3>Nguồn trạng thái LIVE</h3></div></div><div className="status-list"><div><span>Mode</span><b>{s.live.mode}</b></div><Status label="Endpoint tùy chọn" ok={s.live.endpoint_configured}/></div><p className="muted">Nếu TikTok không cấp endpoint LIVE status, để MANUAL và dùng trang “LIVE hiện tại” để Start/Stop phiên. Shop/Ads vẫn có thể chạy thật.</p></section>
  <section className="panel"><div className="panel-head"><div><span className="section-kicker">ALERT THRESHOLDS</span><h3>Ngưỡng cảnh báo</h3></div></div><label>Refund vượt (%)<input type="number" value={t.refund_warning_percent} onChange={e=>setT({...t,refund_warning_percent:+e.target.value})}/></label><label>Ads/GMV vượt (%)<input type="number" value={t.ads_gmv_warning_percent} onChange={e=>setT({...t,ads_gmv_warning_percent:+e.target.value})}/></label><label>GMV 15 phút giảm (%)<input type="number" value={t.gmv_velocity_drop_percent} onChange={e=>setT({...t,gmv_velocity_drop_percent:+e.target.value})}/></label><button className="primary" onClick={saveThresholds}>Lưu thresholds</button></section>
  <section className="panel span-2"><div className="panel-head"><div><span className="section-kicker">AUTO TEAM MAPPING</span><h3>Team phụ trách theo kênh / ca</h3></div></div><div className="assignment-grid"><label>Kênh 01 • Ca sáng{teamSelect('channel_1_ca_sang_team_id')}</label><label>Kênh 01 • Ca tối{teamSelect('channel_1_ca_toi_team_id')}</label><label>Kênh 02 • Ca sáng{teamSelect('channel_2_ca_sang_team_id')}</label><label>Kênh 02 • Ca tối{teamSelect('channel_2_ca_toi_team_id')}</label></div><button className="primary" onClick={saveAssignments}>Lưu phân ca tự động</button></section>
  <section className="panel env-panel span-2"><span className="section-kicker">ENV CHECKLIST</span><h3>Khi API được duyệt</h3><p>Điền các biến sau vào file <code>.env</code>, map Shop Cipher/Advertiser ID trong trang Kênh TikTok, rồi restart Docker.</p><div className="code-list">{envs.map(x=><code key={x}>{x}</code>)}</div></section>
 </div></>
}
