import { useEffect,useState } from 'react'
import { LogOut, RefreshCw } from 'lucide-react'
import { api,clearSession,connectRealtime } from '../api'
import { money,num,pct,duration } from '../utils'
import StatusPill from '../components/StatusPill'
import SnapshotSelect from '../components/SnapshotSelect'
import KpiCard from '../components/KpiCard'

function useTeam(){const [data,setData]=useState(null),[snapshot,setSnapshot]=useState('T3H');const load=()=>api.teamDashboard(snapshot).then(setData);useEffect(()=>{load();const stop=connectRealtime(()=>load());const id=setInterval(load,30000);return()=>{stop();clearInterval(id)}},[snapshot]);return {data,snapshot,setSnapshot,load}}

function TeamDesktop({ctx}){const {data,snapshot,setSnapshot,load}=ctx;const s=data.session,m=s?.metrics;return <div className="team-desktop"><header className="team-top"><div><span className="eyebrow">TEAM DASHBOARD</span><h1>{data.team.name}</h1></div><div className="team-top-actions"><SnapshotSelect value={snapshot} onChange={setSnapshot} compact/><button className="icon-btn" onClick={load}><RefreshCw size={18}/></button><button className="icon-btn" onClick={()=>{clearSession();location.href='/login'}}><LogOut size={18}/></button></div></header>{!s?<div className="empty-state big">Chưa có phiên LIVE</div>:<><section className="team-live-banner"><div><StatusPill status={s.status}/><h2>{s.channel_name} · {s.shift==='MORNING'?'Ca sáng':'Ca tối'}</h2></div><div><small>LIVE TIME</small><strong>{duration(m.duration_seconds)}</strong></div></section><section className="kpi-grid five user-kpis"><KpiCard label="GMV" value={money(m.gmv)}/><KpiCard label="Orders" value={num(m.orders)}/><KpiCard label="Ads" value={money(m.ads_spend)}/><KpiCard label="AOV" value={money(m.aov)}/><KpiCard label="ROAS" value={m.roas}/></section><section className="progress-card"><div><span>Target hôm nay</span><b>{money(data.team.target_gmv)}</b></div><div className="progress-track"><i style={{width:`${Math.min(data.progress_pct,100)}%`}}/></div><strong>{data.progress_pct}%</strong></section><section className="dashboard-two"><div className="panel"><div className="panel-title"><h3>Hiệu quả phiên LIVE</h3></div><div className="team-stat-grid"><span><small>Ads / GMV</small><b>{pct(m.ads_gmv_pct)}</b></span><span><small>Hoàn / Hủy</small><b>{pct(m.refund_rate)}</b></span><span><small>Doanh thu giữ</small><b>{money(m.net_revenue)}</b></span><span><small>GMV / Giờ</small><b>{money(m.gmv_per_hour)}</b></span></div></div><div className="panel"><div className="panel-title"><h3>Top SKU</h3></div><div className="sku-list">{s.top_skus.map((p,i)=><div key={p.sku_id}><span>{i+1}</span><div><b>{p.product_name}</b><small>{num(p.quantity)} sản phẩm</small></div><strong>{money(p.revenue)}</strong></div>)}</div></div></section></>}</div>}

function TeamMobile({ctx}){const {data,snapshot,setSnapshot,load}=ctx;const s=data.session,m=s?.metrics;return <div className="team-mobile"><header><div><span className="eyebrow">TEAM</span><h1>{data.team.name}</h1></div><button className="round-btn" onClick={load}><RefreshCw size={18}/></button></header>{!s?<div className="empty-state big">Chưa có phiên LIVE</div>:<><div className="mobile-live"><div><StatusPill status={s.status}/><span>{s.channel_name}</span></div><strong>{money(m.gmv)}</strong><small>GMV hiện tại</small></div><div className="mobile-snapshot"><SnapshotSelect value={snapshot} onChange={setSnapshot} compact/></div><div className="mobile-kpi-grid"><div><span>Đơn hàng</span><b>{num(m.orders)}</b></div><div><span>AOV</span><b>{money(m.aov)}</b></div><div><span>Ads</span><b>{money(m.ads_spend)}</b></div><div><span>ROAS</span><b>{m.roas}</b></div></div><div className="mobile-card"><div className="mobile-card-head"><span>Tiến độ Target</span><b>{data.progress_pct}%</b></div><div className="progress-track"><i style={{width:`${Math.min(data.progress_pct,100)}%`}}/></div><small>{money(m.gmv)} / {money(data.team.target_gmv)}</small></div><div className="mobile-card"><h3>Sau hoàn/hủy</h3><div className="mobile-big-row"><div><span>Tỷ lệ</span><b>{pct(m.refund_rate)}</b></div><div><span>Doanh thu giữ</span><b>{money(m.net_revenue)}</b></div></div></div><div className="mobile-card"><h3>Top SKU</h3><div className="mobile-skus">{s.top_skus.slice(0,4).map((p,i)=><div key={p.sku_id}><span>{i+1}</span><div><b>{p.product_name}</b><small>{num(p.quantity)} SP</small></div><strong>{money(p.revenue)}</strong></div>)}</div></div><button className="mobile-logout" onClick={()=>{clearSession();location.href='/login'}}><LogOut size={17}/>Đăng xuất</button></>}</div>}

export default function TeamDashboard(){const ctx=useTeam();if(!ctx.data)return <div className="page-loading">Đang tải dashboard...</div>;return <div className="team-shell"><TeamDesktop ctx={ctx}/><TeamMobile ctx={ctx}/></div>}
