const API_BASE = import.meta.env.VITE_API_URL || '/api'
export function getToken(){return localStorage.getItem('lcc_token')}
export function getSessionUser(){try{return JSON.parse(localStorage.getItem('lcc_user')||'null')}catch{return null}}
export function saveSession(token,user){localStorage.setItem('lcc_token',token);localStorage.setItem('lcc_user',JSON.stringify(user))}
export function clearSession(){localStorage.removeItem('lcc_token');localStorage.removeItem('lcc_user')}
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const token=getToken();if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(`${API_BASE}${path}`,{...options,headers});if(res.status===401){clearSession();window.location.href='/login';throw new Error('Phiên đăng nhập đã hết hạn')}if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.detail||`HTTP ${res.status}`)}return res.json()}
async function download(path,filename){const token=getToken();const res=await fetch(`${API_BASE}${path}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export const api={
 login:(username,password)=>request('/auth/login',{method:'POST',body:JSON.stringify({username,password})}),me:()=>request('/auth/me'),overview:(s='T3H')=>request(`/admin/overview?snapshot_type=${s}`),ranking:(params={})=>{const p=new URLSearchParams(params);return request(`/admin/ranking?${p.toString()}`)},sessions:(s='T3H')=>request(`/admin/sessions?snapshot_type=${s}`),session:(id,s='T3H')=>request(`/admin/sessions/${id}?snapshot_type=${s}`),alerts:()=>request('/admin/alerts'),ackAlert:id=>request(`/admin/alerts/${id}/ack`,{method:'POST'}),directory:()=>request('/admin/directory'),status:()=>request('/config/status'),teamDashboard:(s='T3H')=>request(`/team/dashboard?snapshot_type=${s}`),mock:(action,body)=>request(`/mock/${action}`,{method:'POST',body:JSON.stringify(body)}),manualStart:body=>request('/admin/manual-live/start',{method:'POST',body:JSON.stringify(body)}),manualStop:channel_id=>request('/admin/manual-live/stop',{method:'POST',body:JSON.stringify({channel_id})}),orders:()=>request('/admin/orders'),products:()=>request('/admin/products'),ads:()=>request('/admin/ads'),teams:(s='T3H')=>request(`/admin/teams?snapshot_type=${s}`),channels:()=>request('/admin/channels'),updateChannel:(id,body)=>request(`/admin/channels/${id}`,{method:'PATCH',body:JSON.stringify(body)}),assignments:()=>request('/admin/assignments'),updateAssignment:(id,body)=>request(`/admin/assignments/${id}`,{method:'PATCH',body:JSON.stringify(body)}),users:()=>request('/admin/users'),createUser:body=>request('/admin/users',{method:'POST',body:JSON.stringify(body)}),setUserActive:(id,active)=>request(`/admin/users/${id}/active`,{method:'PATCH',body:JSON.stringify({active})}),settings:()=>request('/admin/settings'),updateSetting:(key,value)=>request(`/admin/settings/${key}`,{method:'PUT',body:JSON.stringify({value})}),report:(qs='')=>request(`/admin/reports/summary${qs}`),exportExcel:(qs='')=>download(`/admin/reports/excel${qs}`,'live-report.xlsx'),exportPdf:(qs='')=>download(`/admin/reports/pdf${qs}`,'live-report.pdf')}
export function connectRealtime(onMessage){const token=getToken();if(!token)return()=>{};const base=import.meta.env.VITE_WS_URL||`${location.protocol==='https:'?'wss':'ws'}://${location.host}`;const ws=new WebSocket(`${base}/ws/dashboard?token=${encodeURIComponent(token)}`);ws.onmessage=e=>{try{onMessage(JSON.parse(e.data))}catch{}};const ping=setInterval(()=>{if(ws.readyState===WebSocket.OPEN)ws.send('ping')},25000);return()=>{clearInterval(ping);ws.close()}}
